-- Migration historique de données familiales retirée du dépôt public.
--
-- Elle ne contenait aucun changement de schéma. Les données privées restent
-- dans le système de production et ne doivent être ni exportées ni rejouées
-- depuis ce dépôt. Voir docs/REMEDIATION_CONFIDENTIALITE.md.
